### ISSUE TITLE
Error while integrating Stage View

### ISSUE THREAD

**Issue by arihantjn53** [OfficeDev/Microsoft-Teams-Samples#196]
Facing `Something went wrong. Please try again.` when trying to integrate Stage View in an adaptive card and following [tab-stage-view](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/tab-stage-view/nodejs/server/models/adaptiveCard.js) sample for reference. I have implemented a personal tab and using it in stage view. 

`manifest.json`
 ```
"staticTabs": [
    {
      "contentUrl": "<ngrok-url>/tab-auth/simple",
      "entityId": "simpleAuth",
      "name": "Test Authentication Tab",
      "scopes": [
        "personal"
      ],
      "context": [
        "personalTab",
        "channelTab"
      ],
    }
  ]
```
`adaptiveCardJson`
```
"body": [
  ...,
  {
    type: 'ActionSet',
    actions: [
      {
        type: "Action.Submit",
        title: "Auth Tab",
        data: {
          msteams: {
            type: "invoke",
            value: {
              type: "tab/tabInfoAction",
              tabInfo: {
                contentUrl: "<ngrok-url>/tab-auth/simple",
                websiteUrl: "<ngrok-url>/tab-auth/simple",
                name: "Test Authentication Tab",
                entityId: "simpleAuth"
              }
            }
          }
        }
      }
    ]
  },
]
```
Error Screenshot
![Screenshot 2021-11-15 at 5 33 54 PM](https://user-images.githubusercontent.com/9934563/141779444-0ac1a85f-3984-44f8-8810-cee8a3bf9bd2.png)

**Comment by Prasad-MSFT** [comment]
@arihantjn53 ,Could you please check if you are using proper valid domains in your manifest?

**Comment by arihantjn53** [comment]
@Prasad-MSFT yes, I have added the corresponding ngrok domain in `validDomains` in manifest.json
Also, not sure if related but I get following error in browser console while trying to access stage view. 

```
Uncaught (in promise) Error: Could not resolve 'app.StageViewV2' from state 'app.apps.appId.section'
    at Object.S.transitionTo (1-vendor.min-a609edf.js:1)
    at Object.S.go (1-vendor.min-a609edf.js:1)
    at e.<anonymous> (3.2-app.min-c2c4871.js:1)
    at i (3.2-app.min-c2c4871.js:1)
    at Object.next (3.2-app.min-c2c4871.js:1)
    at 3.2-app.min-c2c4871.js:1
    at new Promise (<anonymous>)
    at s (3.2-app.min-c2c4871.js:1)
    at e.navigateMainWindowWithEntityCommand (3.2-app.min-c2c4871.js:1)
    at e.handleCommandEvent (3.2-app.min-c2c4871.js:1)
```

**Comment by Prasad-MSFT** [comment]
@arihantjn53, We are able to repro the issue at our end and raised a bug for the same. Engineering team is looking into it. We will inform you once we get any update. Thanks!

**Comment by pravinrsingh** [comment]
@Prasad-MSFT any update or ETA?

**Comment by Prasad-MSFT** [comment]
@pravinrsingh - Engineering team is working on the issue. There is no such ETA to share as of now. We will update you once we get any information. Thanks!

**Comment by Abhiram219** [comment]
@Prasad-MSFT 

++ on this issue. I'm also facing the same.

**Comment by i066088** [comment]
@Prasad-MSFT  I am facing this issue too. I think this is a regression issue because it's worked before.
However, for the pinning the stage view as a tab, it has never worked.
I hope this issue can be fixed very soon. Thanks.

**Comment by v-chetsh** [comment]
Hello All,
This issue fix is in progress, we do not have exact ETA to share but will update you.

**Comment by Prasad-MSFT** [comment]
This issue is resolved now with the updated Microsoft Teams Version 1.4.00.34416 (64-bit). Please update your Microsoft Teams client version and check.

**Comment by Prasad-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required.

**Comment by i066088** [comment]
@Prasad-MSFT 
I have updated the version to Microsoft Teams Version 1.5.00.1870 (64-bit). 
The issue still persists.

**Comment by i066088** [comment]
@arihantjn53 could you please verify? The issue is still there in my testing environment. thanks a lot.
